site_name: Dark Theme Mkdocs
repo_name: FernandoCelmer/mkdocs
repo_url: https://github.com/dracula/mkdocs
site_url: https://www.fernandocelmer.com/
copyright: Fernando Celmer

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Release Notes: nav/release-notes.md

theme:
  name: dracula
  logo: assets/img/dracula.png
  favicon: assets/img/favicon.ico
